/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-huracan-twin-turbo-lost-1d3809ea5a6749d9864ec4c32511d716
Title: Lamborghini Huracan Twin Turbo [LOST]
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Car1(props) {
  const { nodes, materials, animations } = useGLTF(
    "/models/car1/lamborghini_huracan_twin_turbo_lost.glb"
  );

  console.log(animations);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PORTA_SX_003_001_blue_0.geometry}
            material={materials.blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PORTA_SX_003_001_mat_black_interior_0.geometry}
            material={materials.mat_black_interior}
          />
        </group>
        <group
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PORTA_SX_001_001_blue_0.geometry}
            material={materials.blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PORTA_SX_001_001_mat_black_interior_0.geometry}
            material={materials.mat_black_interior}
          />
        </group>
        <group
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LW_CARBONIO_COFANGO_1_004_001_blue_0.geometry}
            material={materials.blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["LW_CARBONIO_COFANGO_1_004_001_����������������002_0"]
                .geometry
            }
            material={materials[".002"]}
          />
        </group>
        <group
          position={[-0.001, -1.252, 0.018]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.Carrozzeria_interna_nera1_003_001_mat_black_interior_0
                .geometry
            }
            material={materials.mat_black_interior}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Carrozzeria_interna_nera1_003_001_����������������001_0"]
                .geometry
            }
            material={materials[".001"]}
          />
        </group>
        <group
          position={[1.909, 18.951, -197.623]}
          rotation={[-2.845, 0.01, 3.139]}
          scale={3.069}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["����������_WHITE_EMIS001_0"].geometry}
            material={materials["WHITE_EMIS.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["����������_WHITE_EMIS001_0_1"].geometry}
            material={materials["WHITE_EMIS.001"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_vetro_car_001_001_mat_vetro_car_0.geometry}
          material={materials.mat_vetro_car}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_vetro_car_red_light_0.geometry}
          material={materials.red_light}
          position={[0, -1.807, -0.152]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Lambo_car_CARBONIO_INTERNO_001_001_mat_carbonio_0.geometry
          }
          material={materials.mat_carbonio}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CARROZZERIA_001_001_forged_0.geometry}
          material={materials.forged}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CARROZZERIA_001_001001_blue_0.geometry}
          material={materials.blue}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_CARROZZERIA_001_001_forged_0.geometry}
          material={materials.forged}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_CARROZZERIA_001_001001_blue_0.geometry}
          material={materials.blue}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_INTERNO_001_001_forged_0.geometry}
          material={materials.forged}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dettagli_interni_001_001_panels_0.geometry}
          material={materials.panels}
          position={[0, 65.708, 102.695]}
          rotation={[-2.746, 0, -Math.PI]}
          scale={[100, 100.335, 101.891]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_fari_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.LW_WIDESCREEN_ALLEGERITO_001_001_windows_tint_0.geometry
          }
          material={materials.windows_tint}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carrozzeria_interna_nera1_001_001_mirrors_0.geometry}
          material={materials.mirrors}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BF_COOLING_SISTEM_001_001_mat_cooling_sistem001_0.geometry
          }
          material={materials["mat_cooling_sistem.001"]}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.STEER_HR001_mat_alcantara_0.geometry}
          material={materials.mat_alcantara}
          position={[35.818, 70.792, 31.739]}
          rotation={[0.275, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.interni_palastica_nera1_001_001_mat_carbonio_0.geometry
          }
          material={materials.mat_carbonio}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.cuciture_bottoni_001_001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.cuciture_bottoni_001_001001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pioggia_mat_cuciture_bottoni_no_bake_0.geometry}
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.STO_mat_cuciture_bottoni_no_bake_0.geometry}
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trofeo_mat_cuciture_bottoni_no_bake_0.geometry}
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Plastica_Lucida_Azzurro_001_001_mat_plastica_lucida_e_azzurro_0
              .geometry
          }
          material={materials.mat_plastica_lucida_e_azzurro}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.dettagli_interni_002_001_mat_plastica_nera001_0.geometry
          }
          material={materials["mat_plastica_nera.001"]}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Carrozzeria_interna_nera1_002_001_mat_black_interior_0
              .geometry
          }
          material={materials.mat_black_interior}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.cuciture_bottoni_003_001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Plastica_Lucida_Azzurro_002_001_mat_plastica_lucida_e_azzurro_0
              .geometry
          }
          material={materials.mat_plastica_lucida_e_azzurro}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.asta_cofango_001_001_mat_black_interior_0.geometry}
          material={materials.mat_black_interior}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.asta_cofango_001_001001_jaune_0.geometry}
          material={materials.jaune}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_sx_alcantara_001_001_mat_alcantara_0.geometry}
          material={materials.mat_alcantara}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_sx_black_interior_001_001_mirrors_0.geometry}
          material={materials.mirrors}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_sx_black_interior_002_001_forged_0.geometry}
          material={materials.forged}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_sx_carbonio_001_001_mat_carbonio_0.geometry}
          material={materials.mat_carbonio}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .porta_sx_cuciture_bottoni_001_001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .porta_sx_cuciture_bottoni_001_001001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.porta_sx_dettagli_interni_001_001_mat_dettagli_interni_0
              .geometry
          }
          material={materials.mat_dettagli_interni}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.porta_sx_plastica_nera_001_001_mat_plastica_nera_0.geometry
          }
          material={materials.mat_plastica_nera}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_sx_vetri_001_001_windows_int_0.geometry}
          material={materials.windows_int}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_sx_vetri_002_001_windows_tint_0.geometry}
          material={materials.windows_tint}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_dx_alcantara_001_001_mat_alcantara_0.geometry}
          material={materials.mat_alcantara}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_dx_black_interior_001_001_mirrors_0.geometry}
          material={materials.mirrors}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_dx_black_interior_002_001_forged_0.geometry}
          material={materials.forged}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_dx_carbonio_001_001_mat_carbonio_0.geometry}
          material={materials.mat_carbonio}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .porta_dx_cuciture_bottoni_001_001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .porta_dx_cuciture_bottoni_001_001001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.porta_dx_dettagli_interni_001_001_mat_dettagli_interni_0
              .geometry
          }
          material={materials.mat_dettagli_interni}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.porta_dx_plastica_nera_001_001_mat_plastica_nera_0.geometry
          }
          material={materials.mat_plastica_nera}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_dx_vetro_001_001_windows_int_0.geometry}
          material={materials.windows_int}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.porta_dx_vetro_002_001_windows_tint_0.geometry}
          material={materials.windows_tint}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.cofango_black_interior_001_001_mat_black_interior_0.geometry
          }
          material={materials.mat_black_interior}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cofango_black_interior_001_001001_forged_0.geometry}
          material={materials.forged}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cofango_fanali_001_001_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cofango_fanali_001_001001_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cofango_fanali_001_001002_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_COFANGO_1_001_001_forged_0.geometry}
          material={materials.forged}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_COFANGO_1_001_001001_blue_0.geometry}
          material={materials.blue}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_COFANGO_1_002_001_forged_0.geometry}
          material={materials.forged}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_COFANGO_1_003_001_blue_0.geometry}
          material={materials.blue}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_COFANGO_2_001_001_forged_0.geometry}
          material={materials.forged}
          position={[0, 17.487, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_vetro_car_002_001_windows_tint_0.geometry}
          material={materials.windows_tint}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_vetro_car001_mat_vetro_car_0.geometry}
          material={materials.mat_vetro_car}
          position={[0, -1.807, 0.658]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Alcantara_002_001_mat_alcantara_0.geometry}
          material={materials.mat_alcantara}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Alcantara_002_001001_stars_0.geometry}
          material={materials.stars}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.interni_palastica_nera1_002_001_mat_plastica_nera_0.geometry
          }
          material={materials.mat_plastica_nera}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.cuciture_bottoni_002_001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_fari001_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_fari002_mat_fanali002_0.geometry}
          material={materials["mat_fanali.002"]}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_fari003_mat_fanali001_0.geometry}
          material={materials["mat_fanali.001"]}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_fari004_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BF_BRAKING_FEELING_CCMR_008_001_mat_wheels_0.geometry}
          material={materials.mat_wheels}
          position={[-3.271, -5.379, -287.091]}
          rotation={[-1.566, 0.035, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_MAGNESIUM_RIMS2_004_001001_mat_wheels_0.geometry}
          material={materials.mat_wheels}
          position={[-76.044, 32.551, -143.415]}
          rotation={[-1.566, 0.035, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tire_mat5_005_tire_mat5_0.geometry}
          material={materials.tire_mat5}
          position={[-81.25, 32.759, -143.387]}
          rotation={[-1.566, 0.035, -Math.PI]}
          scale={10.035}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.INNERRIM_RR003_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[-77.366, 32.363, -143.392]}
          rotation={[-1.511, 0.035, -3.125]}
          scale={[90.069, 90.93, 90.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LOGO_RR003_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[-89.936, 34.878, -139.596]}
          rotation={[-1.511, 0.035, -3.125]}
          scale={[90.069, 90.93, 90.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RIM_RR007_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[-92.155, 33.166, -143.387]}
          rotation={[-3.082, 0.003, -3.107]}
          scale={[90.069, 90.93, 90.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WHEEL_RR005_wheels_gold_0.geometry}
          material={materials.wheels_gold}
          position={[-88.907, 33.014, -143.387]}
          rotation={[-1.511, 0.016, -3.125]}
          scale={[90.07, 90.93, 90.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tire_mat5_03_tire_mat5_0.geometry}
          material={materials.tire_mat5}
          position={[81.25, 32.759, -143.387]}
          rotation={[-1.566, -0.035, 0]}
          scale={10.035}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_MAGNESIUM_RIMS2_002_001001_mat_wheels_0.geometry}
          material={materials.mat_wheels}
          position={[76.006, 32.578, -143.361]}
          rotation={[-1.566, -0.035, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BF_BRAKING_FEELING_CCMR_002_001_mat_wheels_0.geometry}
          material={materials.mat_wheels}
          position={[3.271, -6.882, -0.091]}
          rotation={[-1.566, -0.035, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.INNERRIM_LR002_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[77.501, 32.378, -143.352]}
          rotation={[-0.017, 0, 0.035]}
          scale={[90.069, 90.95, 90.95]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RIM_LR004_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[92.098, 33.181, -143.385]}
          rotation={[-0.017, 0, 0.035]}
          scale={[90.069, 90.95, 90.95]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WHEEL_LR003_wheels_gold_0.geometry}
          material={materials.wheels_gold}
          position={[89.043, 33.029, -143.38]}
          rotation={[-0.017, 0, 0.035]}
          scale={[90.069, 90.95, 90.95]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tire_mat5_02_tire_mat5_0.geometry}
          material={materials.tire_mat5}
          position={[80.878, 31.895, 117.112]}
          rotation={[-1.566, -0.035, 0]}
          scale={9.714}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_MAGNESIUM_RIMS2_001_001001_mat_wheels_0.geometry}
          material={materials.mat_wheels}
          position={[78.142, 31.521, 117.084]}
          rotation={[-1.566, -0.035, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BF_BRAKING_FEELING_CCMR_001_001_mat_wheels_0.geometry}
          material={materials.mat_wheels}
          position={[2.784, -5.14, -0.261]}
          rotation={[-1.566, -0.035, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.INNERRIM_LF_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[78.52, 31.78, 116.814]}
          rotation={[1.576, 0.035, -0.001]}
          scale={[79.2, 85, 85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LOGO_LF_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[89.512, 35.701, 118.791]}
          rotation={[1.576, 0.035, -0.001]}
          scale={[79.2, 85, 85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RIM_LF_003_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[91.533, 32.247, 117.075]}
          rotation={[1.576, 0.035, -0.001]}
          scale={[79.2, 85, 85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WHEEL_LF_002_wheels_gold_0.geometry}
          material={materials.wheels_gold}
          position={[88.676, 32.146, 117.04]}
          rotation={[1.576, 0.035, -0.001]}
          scale={[79.2, 85, 85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BF_BRAKING_FEELING_CCMR_007_001_mat_wheels_0.geometry}
          material={materials.mat_wheels}
          position={[-2.784, -6.367, 234.09]}
          rotation={[-1.566, 0.035, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_MAGNESIUM_RIMS2_003_001001_mat_wheels_0.geometry}
          material={materials.mat_wheels}
          position={[-77.957, 31.445, 117.028]}
          rotation={[-1.566, 0.035, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tire_mat5_004_tire_mat5_0.geometry}
          material={materials.tire_mat5}
          position={[-80.776, 31.895, 117.112]}
          rotation={[-1.566, 0.035, -Math.PI]}
          scale={9.62}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.INNERRIM_RF001_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[-78.494, 31.53, 117.121]}
          rotation={[-0.035, 0.001, -0.035]}
          scale={[79.2, 85, 85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LOGO_RF001_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[-89.536, 34.064, 120.552]}
          rotation={[-0.035, 0.001, -0.035]}
          scale={[79.2, 85, 85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RIM_RF003_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[-91.498, 32.253, 117.113]}
          rotation={[-0.035, 0.001, -0.035]}
          scale={[79.2, 85, 85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WHEEL_RF002_wheels_gold_0.geometry}
          material={materials.wheels_gold}
          position={[-88.643, 32.117, 117.115]}
          rotation={[-0.035, 0.001, -0.035]}
          scale={[79.2, 85, 85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BF_BRAKING_FEELING_CCMR_003_001_calipers_0.geometry}
          material={materials.calipers}
          position={[2.784, -5.14, -0.261]}
          rotation={[-1.566, -0.035, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BF_BRAKING_FEELING_CCMR_004_001_calipers_0.geometry}
          material={materials.calipers}
          position={[-2.789, -5.139, -0.321]}
          rotation={[-1.566, 0.035, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BF_BRAKING_FEELING_CCMR_005_001_calipers_0.geometry}
          material={materials.calipers}
          position={[-3.251, -6.882, -0.153]}
          rotation={[-1.566, 0.035, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BF_BRAKING_FEELING_CCMR_006_001_calipers_0.geometry}
          material={materials.calipers}
          position={[3.271, -6.882, -0.091]}
          rotation={[-1.566, -0.035, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.cuciture_bottoni_004_001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.cuciture_bottoni_004_001001_mat_cuciture_bottoni_no_bake_0
              .geometry
          }
          material={materials.mat_cuciture_bottoni_no_bake}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GEO_Arrow_RPM_INT_DISPLAY_AT_0.geometry}
          material={materials.INT_DISPLAY_AT}
          position={[35.861, 68.128, 57.967]}
          rotation={[-1.143, 1.027, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GEO_RPM_Slide_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[35.861, 68.107, 58.012]}
          rotation={[1.998, 1.395, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RPM_Mask_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[35.861, 68.107, 58.012]}
          rotation={[1.998, 1.395, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GEO_INT_GAUGE_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RPM_BLUE_2_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_V_Neg_0_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_V_Neg_1_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_V_Neg_2_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_V_Neg_3_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_V_Pos_0_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_V_Pos_1_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_V_Pos_2_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_V_Pos_3_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_H_Neg_3_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_H_Neg_2_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_H_Neg_1_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_H_Neg_0_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_H_Pos_0_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_H_Pos_1_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_H_Pos_2_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Led_H_Pos_3_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RPM_BLUE_0_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RPM_BLUE_1_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GEO_DISPLAY_BACK_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GEO_Display_Mask_INT_DISPLAY_AT_0.geometry}
          material={materials.INT_DISPLAY_AT}
          position={[-0.124, 13.383, 111.284]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WATER_9_INT_DISPLAY_0.geometry}
          material={materials.INT_DISPLAY}
          position={[-0.124, 13.383, 111.284]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object001_black001_0.geometry}
          material={materials["black.001"]}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dettagli_interni_003_001_forged_0.geometry}
          material={materials.forged}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Carrozzeria_interna_nera1_003_001001_bouchon_0.geometry
          }
          material={materials.bouchon}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carrozzeria_interna_nera1_003_001002_cable_0.geometry}
          material={materials.cable}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carrozzeria_interna_nera1_003_001003_fil_0.geometry}
          material={materials.material}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Carrozzeria_interna_nera1_003_001004_mat_black_interior_0
              .geometry
          }
          material={materials.mat_black_interior}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Carrozzeria_interna_nera1_003_001005_bar_stabe_0.geometry
          }
          material={materials.bar_stabe}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Carrozzeria_interna_nera1_003_001006_mat_black_interior_0
              .geometry
          }
          material={materials.mat_black_interior}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Carrozzeria_interna_nera1_003_001007_mat_black_interior_0
              .geometry
          }
          material={materials.mat_black_interior}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carrozzeria_interna_nera1_003_001008_black_0.geometry}
          material={materials.black}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Plastica_Lucida_Azzurro_003_001_mat_plastica_lucida_e_azzurro_0
              .geometry
          }
          material={materials.mat_plastica_lucida_e_azzurro}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Plastica_Lucida_Azzurro_003_001001_mat_plastica_lucida_e_azzurro_0
              .geometry
          }
          material={materials.mat_plastica_lucida_e_azzurro}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CARROZZERIA_002_001_blue_0.geometry}
          material={materials.blue}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_CARROZZERIA_002_001_blue001_0.geometry}
          material={materials["blue.001"]}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_CARROZZERIA_003_001_body2_0.geometry}
          material={materials.body2}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_CARROZZERIA_004_001_blue_0.geometry}
          material={materials.blue}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LW_CARBONIO_CARROZZERIA_005_001_blue_0.geometry}
          material={materials.blue}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CARROZZERIA_003_001_blue_0.geometry}
          material={materials.blue}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_fari004001_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_fari004002_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_fari004003_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BLOOM_fari004004_mat_fanali_0.geometry}
          material={materials.mat_fanali}
          position={[0, -1.807, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rb2_ledsiplayicon001_0.geometry}
          material={materials["ledsiplayicon.001"]}
          position={[33.594, 72.53, 59.973]}
          rotation={[-3.029, 0.002, 3.141]}
          scale={[94.808, 94.807, 94.808]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.l1_ledsiplayicon001_0.geometry}
          material={materials["ledsiplayicon.001"]}
          position={[38.541, 72.53, 59.973]}
          rotation={[-3.029, 0.002, 3.141]}
          scale={[94.808, 94.807, 94.808]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tcoff_ledsiplayicon002_0.geometry}
          material={materials["ledsiplayicon.002"]}
          position={[45.787, 74.559, 60.514]}
          rotation={[-3.029, 0.002, 3.141]}
          scale={[94.808, 94.807, 94.808]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lam_sestoelemento_11_lod0_body_misc__misc_0.geometry}
          material={materials.misc}
          position={[-1.613, 20.484, -172.496]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.lam_sestoelemento_11_lod0_body_rubber_trim__rubber_trim_0
              .geometry
          }
          material={materials.rubber_trim}
          position={[-2.189, 26.339, -168.112]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rear_oil_catch_can_misc_0.geometry}
          material={materials.misc}
          position={[-32.675, 51.664, -144.781]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rear_gear_plug_matte_colors_0.geometry}
          material={materials.matte_colors}
          position={[4.019, 27.729, -169.828]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rear_gear_bracket_misc_0.geometry}
          material={materials.misc}
          position={[-0.027, 40, -157.853]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={[84.046, 100, 100]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rear_gear_steel_structer_forged_0.geometry}
          material={materials.forged}
          position={[-0.027, 64.012, -189.295]}
          rotation={[2.813, 0, Math.PI]}
          scale={[136.257, 31.676, 114.104]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rear_structure_plate_misc_0.geometry}
          material={materials.misc}
          position={[-16.92, 42.131, -116.847]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["REN_A442B_ENGINE_LADX001_Material_#7_0"].geometry}
          material={materials.Material_7}
          position={[-0.027, -2.287, -14.259]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["REN_A442B_CHASSIS_LADX_Material_#8_0"].geometry}
          material={materials.Material_8}
          position={[-0.036, -6.577, -15.968]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.REN_A442B_CHASSIS_LADX001_forged_0.geometry}
          material={materials.forged}
          position={[-0.036, -6.577, -15.968]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["rear_tubechasis_tringle_gearbase_Material_#8_0"].geometry
          }
          material={materials.Material_8}
          position={[-2.225, 33.851, -175.44]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.turbo_SUB0_1blue_0.geometry}
          material={materials["1blue"]}
          position={[-26.87, 43.469, -180.22]}
          rotation={[-1.867, 0.016, -1.559]}
          scale={[106.705, 106.705, 118.561]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.turbo_SUB1_exhaustpipes_0.geometry}
          material={materials.exhaustpipes}
          position={[-26.87, 43.469, -180.22]}
          rotation={[-1.867, 0.016, -1.559]}
          scale={[106.705, 106.705, 118.561]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .AirFilter_02_Untitled_025_SUB0_chevrolet_c10reward_2016engine_material001_0
              .geometry
          }
          material={materials["chevrolet_c10reward_2016engine_material.001"]}
          position={[-50.954, 51.227, -180.72]}
          rotation={[1.814, -0.344, -1.504]}
          scale={[106.852, 105.536, 100.825]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.AirFilter_02_Untitled_025_SUB3_exhaustpipes_0.geometry
          }
          material={materials.exhaustpipes}
          position={[-50.954, 51.227, -180.72]}
          rotation={[1.814, -0.344, -1.504]}
          scale={[106.852, 105.536, 100.825]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.AirFilter_02_Untitled_025_SUB1_airfilterxxR_0.geometry
          }
          material={materials.airfilterxxR}
          position={[-50.954, 51.227, -180.72]}
          rotation={[1.814, -0.344, -1.504]}
          scale={[106.852, 105.536, 100.825]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .AirFilter_02_Untitled_025_SUB2_chevrolet_c10reward_2016engine_material001_0
              .geometry
          }
          material={materials["chevrolet_c10reward_2016engine_material.001"]}
          position={[-50.954, 51.227, -180.72]}
          rotation={[1.814, -0.344, -1.504]}
          scale={[106.852, 105.536, 100.825]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Turbo_exhaust_housing1_chevrolet_c10reward_2016engine_material001_0
              .geometry
          }
          material={materials["chevrolet_c10reward_2016engine_material.001"]}
          position={[-16.574, 41.732, -180.024]}
          rotation={[0.006, -0.093, -1.543]}
          scale={[106.706, 106.7, 118.956]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boltsxx021_Material_#221_0"].geometry}
          material={materials.Material_221}
          position={[-20.102, 39.269, -174.464]}
          rotation={[1.804, -0.053, 1.553]}
          scale={[44.263, 74.45, 83.214]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Turbo_exhaust_manifold001_turbo_exhaust_manifold_0.geometry
          }
          material={materials.turbo_exhaust_manifold}
          position={[-17.222, 37.068, -170.176]}
          rotation={[3.121, 0.12, -1.583]}
          scale={[106.668, 106.707, 118.787]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Turbo_exhaust_maniflod_bolt1_turbo_exhaustSide_0.geometry
          }
          material={materials.turbo_exhaustSide}
          position={[-19.414, 34.913, -174.745]}
          rotation={[1.809, -0.017, -1.608]}
          scale={[44.247, 74.451, 83.248]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Turbo_intake_housingR_chevrolet_c10reward_2016engine_material001_0
              .geometry
          }
          material={materials["chevrolet_c10reward_2016engine_material.001"]}
          position={[-26.87, 43.718, -180.767]}
          rotation={[3.017, -0.009, -1.588]}
          scale={[106.571, 106.709, 118.783]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AirIntake_pipe_exhaustpipes_0.geometry}
          material={materials.exhaustpipes}
          position={[-41.64, 50.09, -179.876]}
          rotation={[-2.838, 0.068, -0.091]}
          scale={[9.159, 9.235, 9.307]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.exhaust_exhaustpipes_0.geometry}
          material={materials.exhaustpipes}
          position={[-11.745, 32.893, -182.883]}
          rotation={[-2.807, -0.002, -1.868]}
          scale={[0.962, 1.041, 1.047]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.turboTocooler_pipe1_exhaustpipes_0.geometry}
          material={materials.exhaustpipes}
          position={[-28.361, 59.898, -182.388]}
          rotation={[2.603, -0.365, 0.024]}
          scale={[1.214, 1.206, 1.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.turbo3_SUB0_chevrolet_c10reward_2016engine_material001_0
              .geometry
          }
          material={materials["chevrolet_c10reward_2016engine_material.001"]}
          position={[26.483, 42.977, -181.095]}
          rotation={[-0.975, -0.015, 1.578]}
          scale={[106.705, 106.705, 118.562]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.turbo3_SUB1_Turbo_oilfeed_block_bllk_0.geometry}
          material={materials.Turbo_oilfeed_block_bllk}
          position={[22.231, 37.751, -179.833]}
          rotation={[-1.769, 0.054, 1.545]}
          scale={[125.327, 106.705, 112.873]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Turbo_exhaust_housing002_chevrolet_c10reward_2016engine_material001_0
              .geometry
          }
          material={materials["chevrolet_c10reward_2016engine_material.001"]}
          position={[16.164, 44.652, -179.716]}
          rotation={[0.351, 0.025, 1.558]}
          scale={[107.006, 106.701, 118.556]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boltsxx011_SUB1_Material_#221_0"].geometry}
          material={materials.Material_221}
          position={[11.828, 38.789, -176.383]}
          rotation={[1.684, 0.078, 0.004]}
          scale={[44.287, 72.856, 84.953]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Boltsxx011_SUB0_turbo_exhaustSide_0.geometry}
          material={materials.turbo_exhaustSide}
          position={[11.828, 38.789, -176.383]}
          rotation={[1.684, 0.078, 0.004]}
          scale={[44.287, 72.856, 84.953]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Turbo_exhaust_manifold_turbo_exhaust_manifold_0.geometry
          }
          material={materials.turbo_exhaust_manifold}
          position={[15.877, 47.165, -168.696]}
          rotation={[3.046, 0.099, -1.502]}
          scale={[105.267, 106.7, 120.839]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AirIntake_pipe001_exhaustpipes_0.geometry}
          material={materials.exhaustpipes}
          position={[36.948, 44.115, -179.903]}
          rotation={[0.113, -0.023, 3.095]}
          scale={[9.152, 9.065, 9.436]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AirFilter_02_Untitled_026_SUB1_airfilterxx_0.geometry}
          material={materials.airfilterxx}
          position={[51.514, 51.001, -178.672]}
          rotation={[1.564, 0.367, 1.651]}
          scale={[107.377, 107.153, 98.878]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .AirFilter_02_Untitled_026_SUB0_chevrolet_c10reward_2016engine_material001_0
              .geometry
          }
          material={materials["chevrolet_c10reward_2016engine_material.001"]}
          position={[51.514, 51.001, -178.672]}
          rotation={[1.564, 0.367, 1.651]}
          scale={[107.377, 107.153, 98.878]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.AirFilter_02_Untitled_026_SUB3_exhaustpipes_0.geometry
          }
          material={materials.exhaustpipes}
          position={[51.514, 51.001, -178.672]}
          rotation={[1.564, 0.367, 1.651]}
          scale={[107.377, 107.153, 98.878]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .AirFilter_02_Untitled_026_SUB2_chevrolet_c10reward_2016engine_material001_0
              .geometry
          }
          material={materials["chevrolet_c10reward_2016engine_material.001"]}
          position={[51.514, 51.001, -178.672]}
          rotation={[1.564, 0.367, 1.651]}
          scale={[107.377, 107.153, 98.878]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tube001x_exhaustpipes_0.geometry}
          material={materials.exhaustpipes}
          position={[27.717, 44.217, -199.883]}
          rotation={[-1.541, 0.203, -1.375]}
          scale={[5.928, 5.564, 5.142]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.intercooler_rear_pipes_SUB0_intercooler_rear_pipe_chrome_0
              .geometry
          }
          material={materials.intercooler_rear_pipe_chrome}
          position={[-1.894, 68.331, -143.828]}
          rotation={[-0.559, -1.556, 1.26]}
          scale={[100, 99.999, 86.653]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.intercooler_rear_pipes_SUB1_intercooler_rubber_x_0.geometry
          }
          material={materials.intercooler_rubber_x}
          position={[-1.894, 68.331, -143.828]}
          rotation={[-0.559, -1.556, 1.26]}
          scale={[100, 99.999, 86.653]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.exh_a_l_shiny001_1blue_0.geometry}
          material={materials["1blue"]}
          position={[6.642, 63.943, -187.459]}
          rotation={[-0.187, -1.305, 1.616]}
          scale={[98.596, 47.789, 72.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.exh_a_l_shiny003_1blue_0.geometry}
          material={materials["1blue"]}
          position={[-8.446, 64.092, -187.735]}
          rotation={[2.835, -1.297, -1.638]}
          scale={[98.594, 48.228, 71.924]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.intercool_Rx1_SUB0_intercooler_aluminum_housing_0.geometry
          }
          material={materials.intercooler_aluminum_housing}
          position={[16.136, 67.928, -172.884]}
          rotation={[2.904, -0.234, -1.586]}
          scale={[99.997, 87.151, 99.531]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.intercool_Rx1_SUB2_blue_0.geometry}
          material={materials.blue}
          position={[16.136, 67.928, -172.884]}
          rotation={[2.904, -0.234, -1.586]}
          scale={[99.997, 87.151, 99.531]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.intercool_Rx1_SUB1_exhaustpipes_0.geometry}
          material={materials.exhaustpipes}
          position={[16.136, 67.928, -172.884]}
          rotation={[2.904, -0.234, -1.586]}
          scale={[99.997, 87.151, 99.531]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.intercooler_middlex_SUB0_intercooler_aluminum_housing_0
              .geometry
          }
          material={materials.intercooler_aluminum_housing}
          position={[-0.65, 68.759, -168.972]}
          rotation={[2.879, -0.021, -1.492]}
          scale={[99.956, 87.652, 99.194]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.intercooler_middlex_SUB1_intercooler_aluminum_mesh_0.geometry
          }
          material={materials.intercooler_aluminum_mesh}
          position={[-0.65, 68.759, -168.972]}
          rotation={[2.879, -0.021, -1.492]}
          scale={[99.956, 87.652, 99.194]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.intercooler_L_SUB0_intercooler_aluminum_housing_0.geometry
          }
          material={materials.intercooler_aluminum_housing}
          position={[-17.651, 67.81, -173.445]}
          rotation={[2.848, 0.226, -1.51]}
          scale={[99.993, 89.02, 98.045]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.intercooler_L_SUB2_blue_0.geometry}
          material={materials.blue}
          position={[-17.651, 67.81, -173.445]}
          rotation={[2.848, 0.226, -1.51]}
          scale={[99.993, 89.02, 98.045]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.intercooler_L_SUB1_exhaustpipes_0.geometry}
          material={materials.exhaustpipes}
          position={[-17.651, 67.81, -173.445]}
          rotation={[2.848, 0.226, -1.51]}
          scale={[99.993, 89.02, 98.045]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.intercooler_middlex001_SUB0_intercooler_aluminum_housing_0
              .geometry
          }
          material={materials.intercooler_aluminum_housing}
          position={[-0.65, 65.646, -168.971]}
          rotation={[2.863, 0.008, -1.573]}
          scale={[100.016, 87.704, 99.088]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.intercooler_middlex001_SUB1_intercooler_aluminum_mesh_0
              .geometry
          }
          material={materials.intercooler_aluminum_mesh}
          position={[-0.65, 65.646, -168.971]}
          rotation={[2.863, 0.008, -1.573]}
          scale={[100.016, 87.704, 99.088]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tube001_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[-7.719, 61.162, -189.637]}
          rotation={[2.955, -0.146, 1.186]}
          scale={[1.381, 1.599, 2.493]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tube002_wheel_lip_0.geometry}
          material={materials.wheel_lip}
          position={[6.02, 61.02, -189.204]}
          rotation={[2.958, -0.127, 1.938]}
          scale={[1.381, 1.599, 2.493]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.intake_bloker_Blkk_Plastic_gal_0.geometry}
          material={materials.Plastic_gal}
          position={[-10.857, 70.986, -145.015]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[126.174, 21.789, 96.242]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.turbo_huosing_right_1blue_0.geometry}
          material={materials["1blue"]}
          position={[26.595, 42.455, -180.692]}
          rotation={[-1.84, -0.005, 1.552]}
          scale={[117.67, 106.709, 119.763]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["turbo_oil_feed_Material_#7_0"].geometry}
          material={materials.Material_7}
          position={[19.7, 49.459, -173.252]}
          rotation={[0.689, 1.121, -0.679]}
          scale={62.431}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["turbo_oil_feed001_Material_#7_0"].geometry}
          material={materials.Material_7}
          position={[-20.291, 52.359, -177.45]}
          rotation={[1.692, 1.159, -2.253]}
          scale={62.431}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plate_plate_0.geometry}
          material={materials.plate}
          position={[73.164, 27.254, -181.39]}
          rotation={[-1.147, -0.005, 3.131]}
          scale={[73, 29, 91]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.lam_gallardolp570_11_lod0_exhaustLa_black__001_exhaustpipes_0
              .geometry
          }
          material={materials.exhaustpipes}
          position={[1.771, 4.584, -104.105]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={[100, 100, 48.112]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.lam_gallardolp570_11_lod0_exhaustRa_black__001_exhaustpipes_0
              .geometry
          }
          material={materials.exhaustpipes}
          position={[0.18, 4.09, -105.799]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={[100, 100, 48.112]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kolon_9001_SUB1_blue_0.geometry}
          material={materials.blue}
          position={[-25.986, 76.493, -44.089]}
          scale={0.61}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kolon_9001_SUB4_cloth_0.geometry}
          material={materials.cloth}
          position={[-25.986, 76.493, -44.016]}
          scale={0.61}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kolon_9001_SUB3_emiss_0.geometry}
          material={materials.emiss}
          position={[-25.986, 76.493, -44.437]}
          scale={0.61}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kolon_9001_SUB2_blue_0.geometry}
          material={materials.blue}
          position={[-25.986, 76.493, -44.181]}
          scale={0.61}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_mat_carbonio001_0.geometry}
          material={materials["mat_carbonio.001"]}
          position={[0, 78.948, -144.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[72, 49, 100]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.lam_gallardolp570_11_lod0_body_chrome__001_wheel_lip001_0
              .geometry
          }
          material={materials["wheel_lip.001"]}
          position={[0.245, 87.217, -217.471]}
          rotation={[2.011, 0, Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kolon_9_forged_0.geometry}
          material={materials.forged}
          position={[-0.212, 75.045, -45.769]}
          scale={0.605}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.LW_CARBONIO_COFANGO_1_002_001002_WHITE_EMIS_0.geometry
          }
          material={materials.WHITE_EMIS}
          position={[7, -0.824, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["������������������_����������������_0"].geometry}
          material={materials.material_66}
          position={[-93.227, 26.687, 65.005]}
          rotation={[2.602, -1.516, -2.071]}
          scale={9.777}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["������������������001_����������������_0"].geometry}
          material={materials.material_66}
          position={[93.201, 26.687, 65.005]}
          rotation={[2.598, 1.517, -0.99]}
          scale={9.777}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.LW_CARBONIO_COFANGO_1_002_001001_WHITE_EMIS003_0.geometry
          }
          material={materials["WHITE_EMIS.003"]}
          position={[1.626, 23.784, -196.196]}
          rotation={[-0.076, -0.011, -0.001]}
          scale={[-100, 100, 100]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.LW_CARBONIO_COFANGO_1_002_001003_WHITE_EMIS002_0.geometry
          }
          material={materials["WHITE_EMIS.002"]}
          position={[36.057, 69.323, -35.408]}
          rotation={[-3.065, 0.011, 3.141]}
          scale={[-53.852, 53.852, 53.852]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.LW_CARBONIO_COFANGO_1_002_001004_WHITE_EMIS002_0.geometry
          }
          material={materials["WHITE_EMIS.002"]}
          position={[-36.947, 69.323, -33.668]}
          rotation={[-3.065, 0.011, 3.141]}
          scale={[-53.052, 53.052, 53.052]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["������������������002_����������������_0"].geometry}
          material={materials.material_66}
          position={[-6.304, 17.245, -197.55]}
          rotation={[Math.PI, 0.011, -Math.PI / 2]}
          scale={4.939}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["��������������_����������������003_0"].geometry}
          material={materials[".003"]}
          position={[70.568, 57.022, 172.379]}
          rotation={[Math.PI / 2, -0.873, 0]}
          scale={[-0.242, 0.242, 3.309]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["��������������001_����������������003_0"].geometry}
          material={materials[".003"]}
          position={[-70.515, 57.022, 172.379]}
          rotation={[Math.PI / 2, 0.873, 0]}
          scale={[0.242, 0.242, 3.309]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Alcantara_002_001002_mat_alcantara_0.geometry}
          material={materials.mat_alcantara}
          position={[0, -2.269, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Lambo_car_CARBONIO_INTERNO_001_001001_mat_carbonio_0.geometry
          }
          material={materials.mat_carbonio}
          position={[0, -0.924, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.LW_CARBONIO_COFANGO_1_002_001005_WHITE_EMIS004_0.geometry
          }
          material={materials["WHITE_EMIS.004"]}
          position={[-0.512, 31.202, 202.759]}
          rotation={[-0.349, 0.001, -0.002]}
          scale={217.196}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/car1/lamborghini_huracan_twin_turbo_lost.glb");
