/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alexander Komendant (SashaRX) (https://sketchfab.com/Sasharx)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/abandoned-snow-carraw-ac643ae6e6854b6bb3210bc1028fbe82
Title: Abandoned Snow Car[RAW]
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Car2(props) {
  const { nodes, materials, animations } = useGLTF(
    "/models/car2/abandoned_snow_carraw.glb"
  );
  console.log(animations);
  return (
    <group {...props} dispose={null}>
      <group rotation={[2.91655, -0.09193, -0.02424]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material0_0.geometry}
            material={materials.material0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material0_0_1.geometry}
            material={materials.material0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material0_0_2.geometry}
            material={materials.material0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material0_0_3.geometry}
            material={materials.material0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material0_0_4.geometry}
            material={materials.material0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material0_0_5.geometry}
            material={materials.material0}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/car2/abandoned_snow_carraw.glb");
